version: "3"

services:
  web:
    image: node:14-alpine
    volumes:
      - ./:/usr/local/app/
    command: sh -c "cd //usr//local//app && npm i && npm run dev"
    ports:
      - "3000:3000"

  redis-server:
    image: redis:alpine
    command: redis-server
    ports:
      - "6379:6379"
